CREATE TABLE utxos (
  utxo_ref PLUTUS.TRANSACTION_INPUT PRIMARY KEY,
  value PLUTUS.VALUE NOT NULL,
  address PLUTUS.ADDRESS NOT NULL,
  datum PLUTUS.OUTPUT_DATUM NOT NULL,

  created_at PLUTUS.SLOT NOT NULL,
  deleted_at PLUTUS.SLOT
);
