SET SEARCH_PATH TO PLUTUS;

-- Drop types in reverse order of their dependencies
DROP TYPE IF EXISTS TX_IN_INFO;
DROP TYPE IF EXISTS TRANSACTION_OUTPUT;
DROP TYPE IF EXISTS OUTPUT_DATUM;
DROP TYPE IF EXISTS TRANSACTION_INPUT;
DROP TYPE IF EXISTS VALUE;
DROP TYPE IF EXISTS ASSET_QUANTITY;
DROP TYPE IF EXISTS Address;
DROP TYPE IF EXISTS STAKING_CREDENTIAL;
DROP TYPE IF EXISTS CHAIN_POINTER;
DROP TYPE IF EXISTS CREDENTIAL;

-- Drop domains
DROP DOMAIN IF EXISTS PLUTUS_DATA;
DROP DOMAIN IF EXISTS SLOT;
DROP DOMAIN IF EXISTS DATUM_HASH;
DROP DOMAIN IF EXISTS SCRIPT_HASH;
DROP DOMAIN IF EXISTS ED25519_PUBKEYHASH;
DROP DOMAIN IF EXISTS TRANSACTION_HASH;
DROP DOMAIN IF EXISTS TOKEN_NAME;
DROP DOMAIN IF EXISTS CURRENCY_SYMBOL;
DROP DOMAIN IF EXISTS HASH32;
DROP DOMAIN IF EXISTS HASH28;

-- Drop the schema
DROP SCHEMA IF EXISTS PLUTUS CASCADE;
