-- Drop types in reverse order of their dependencies
DROP TYPE IF EXISTS PLUTUS.TX_IN_INFO;
DROP TYPE IF EXISTS PLUTUS.TRANSACTION_OUTPUT;
DROP TYPE IF EXISTS PLUTUS.OUTPUT_DATUM;
DROP TYPE IF EXISTS PLUTUS.TRANSACTION_INPUT;
DROP TYPE IF EXISTS PLUTUS.VALUE;
DROP TYPE IF EXISTS PLUTUS.ASSET_QUANTITY;
DROP TYPE IF EXISTS PLUTUS.Address;
DROP TYPE IF EXISTS PLUTUS.STAKING_CREDENTIAL;
DROP TYPE IF EXISTS PLUTUS.CHAIN_POINTER;
DROP TYPE IF EXISTS PLUTUS.CREDENTIAL;

-- Drop domains
DROP DOMAIN IF EXISTS PLUTUS.PLUTUS_DATA;
DROP DOMAIN IF EXISTS PLUTUS.SLOT;
DROP DOMAIN IF EXISTS PLUTUS.DATUM_HASH;
DROP DOMAIN IF EXISTS PLUTUS.SCRIPT_HASH;
DROP DOMAIN IF EXISTS PLUTUS.ED25519_PUBKEYHASH;
DROP DOMAIN IF EXISTS PLUTUS.TRANSACTION_HASH;
DROP DOMAIN IF EXISTS PLUTUS.TOKEN_NAME;
DROP DOMAIN IF EXISTS PLUTUS.CURRENCY_SYMBOL;
DROP DOMAIN IF EXISTS PLUTUS.HASH32;
DROP DOMAIN IF EXISTS PLUTUS.HASH28;

-- Drop the schema
DROP SCHEMA IF EXISTS PLUTUS CASCADE;
