CREATE TABLE utxos (
  utxo_ref PLUTUS.TRANSACTION_INPUT PRIMARY KEY,
  value PLUTUS.VALUE NOT NULL,
  address TEXT NOT NULL,
  datum PLUTUS.OUTPUT_DATUM NOT NULL,

  created_at CARDANO.SLOT NOT NULL,
  deleted_at CARDANO.SLOT
);
